# IntelliJ Platform Artifacts Repositories
# -> https://plugins.jetbrains.com/docs/intellij/intellij-artifacts.html

pluginGroup = dev.jbang.intellij.plugins
pluginName = jbang-idea-plugin
pluginRepositoryUrl = https://github.com/jbangdev/jbang-idea
# SemVer format -> https://semver.org
pluginVersion = 0.25.2

# See https://plugins.jetbrains.com/docs/intellij/build-number-ranges.html
# 262 = 2026.2, the first build where this plugin's platform APIs are available.
pluginSinceBuild = 262
# leaving blank to make installable in EAP
pluginUntilBuild =

# IntelliJ Platform Properties -> https://plugins.jetbrains.com/docs/intellij/tools-intellij-platform-gradle-plugin.html
platformVersion = 2026.2

# Plugin Dependencies -> https://plugins.jetbrains.com/docs/intellij/plugin-dependencies.html
platformBundledPlugins = com.intellij.java,com.intellij.modules.json,org.jetbrains.idea.reposearch,org.jetbrains.kotlin,org.intellij.groovy,com.intellij.gradle
platformBundledModules = intellij.repository.search.completion

# Gradle Releases -> https://github.com/gradle/gradle/releases
gradleVersion = 9.6.1

# Opt-out flag for bundling Kotlin standard library.
# See https://plugins.jetbrains.com/docs/intellij/kotlin.html#kotlin-standard-library for details.
# suppress inspection "UnusedProperty"
kotlin.stdlib.default.dependency = false
